### ISSUE TITLE
Error  COM_ARS_UPDATESTREAM_ERR_JEDID_EMPTY

### ISSUE THREAD

**Issue by uglyeoin** [akeeba/release-system#111]
In update streams if I leave the JED part blank I get an error message, yet your documentation says this part is optional.  The language string is also unavailable by the seems of things as it shows literal.

Error

COM_ARS_UPDATESTREAM_ERR_JEDID_EMPTY

**Comment by nikosdion** [comment]
Sorry for the late reply. I believe an unfortunate issue with my mail client filtered out emails from this project :/

The code is working differently with 0 and empty string. If you set it to 0 it won't complain. If you set it to an empty string it throws an error. I know about this little quirk and how to fix it. I hadn't had the chance to do it yet. Thank you for reminding me!
