### ISSUE TITLE
Release - Copy - Must have unique alias

### ISSUE THREAD

**Issue by uglyeoin** [akeeba/release-system#112]
It seems the copy button does not work under the releases panel.  I'm not saying this as a complaint only to try and help.  It wan't a unique alias, which you cannot do using the copy button alone, you need to enter the file and do a "save and new" with a new alias.

**Comment by nikosdion** [comment]
Yes, that's the downside of better pre-save checks necessary to prevent routing issues. I should just remove all these copy buttons.

**Comment by nikosdion** [comment]
FWIW the best way to manage releases is automatically, e.g. using [Akeeba Release Maker](https://github.com/akeeba/releasemaker). This is fully supported by [common Phing script of Akeeba BuildFIles](https://github.com/akeeba/buildfiles/tree/master/phing) and is, in fact, the main way we publish software on our site.

**Comment by uglyeoin** [comment]
Thank you, I will look at that and try to get it working.  Thanks for the software, you the man.
