### ISSUE TITLE
Stopped working with Falang

### ISSUE THREAD

**Issue by gruz** [akeeba/release-system#115]
ARS v.3.2.3
Falang: 2.8.4

After update from an older versions  it stopped working. Falang still has translations in backend, but ARS pages are now untranslated at frontend. Tested on a fresh install as well. I suspect ARS (FOF?) now in some way avoids native Joomla way to make queries, which are intercepted by a Falang database driver plugin.

**Comment by nikosdion** [comment]
Can you please show me where exactly we are bypassing the Joomla! database driver? FOF 3 components use the [FOF 3 Container's `db` service](https://github.com/akeeba/fof/blob/development/fof/Container/Container.php#L516) which is populated by a call to [`FOF30\Platform\Joomla\Platform::getDBO`](https://github.com/akeeba/fof/blob/development/fof/Platform/Joomla/Platform.php#L420) which returns the Joomla! database driver object through JFactory. So, we end up using the same object returned by `JFactory::getDBO()` which is the One True Joomla! Way of getting the database object.

One thing to note here is that the Container object for ARS may be initialized by a plugin. We have a bunch of plugins. However, if it affects all pages it must be the system plugin arsjed ("System - Akeeba Release System integration with Install from Web"). If this is published with an ordering _before_ Falang's system plugin then you are initializing the Container and, by extend, the database object used by ARS before Falang has the chance to do its hack-ish replacement of the Joomla! database object.

My recommendation: reorder the system plugins, putting Falang before any other plugin. If that doesn't work please contact the Falang developer. Last time I looked at Falang it was about 2 years ago. Sorry!

**Comment by nikosdion** [comment]
I am closing this due to lack of response. If you have more information about this issue feel free to add a comment and I will reopen this.

**Comment by gruz** [comment]
> reorder the system plugins, putting Falang before any other plugin

This helped. Thanks.
