### ISSUE TITLE
Unable to select folder for upload after move to latest Ubuntu 16.04 with php 7.x

### ISSUE THREAD

**Issue by janweigner** [akeeba/release-system#117]
After a forced move of VMs I had to use the latest service providers Ubuntu 16.04LTS image as base which now comes with php 7.x by default. Akeebabackup Pro restore was no problem and ARS functionality seemed 100% OK. Users have been accessing it and downloading stuff as usual. Now the BUT. 

When having to upload additional content to ARS it is impossible to upload anything as I cannot choose any sub-directory and it does also not show me the existing content of any folder. 

Must be something trivial, but for the life of me I can't find it. Anyone any ideas or pointers?

Thanks in advance.

**Comment by nikosdion** [comment]
I am of course developing on PHP 7.1 and hosted on 7.0, so the PHP version is irrelevant. Most likely you have an onwership / permissions issue of the folders hosting the files you make available for download. If you have put your files outside your web root please also check if you have open_basedir restrictions which may be preventing PHP from accessing off-site folders at all.

**Comment by janweigner** [comment]
Thanks for the quick reply.

Joomla is installed straight in in /var/www/html
The folder for all my ARS files is /var/www/html/arsrepo
Permissions are set by Akeeba Admin Tools to 755 for folders and 644 for files and owner/group  is www-data

I still have another working instance of ARS which is running under Ubuntu 14.04 and PHP 5.5 and I did compare the PHP settings and they look identical apart from where the "Session Save Path" points.

Best regards,
Jan

________________________________

**Comment by nikosdion** [comment]
All ARS does is call JFolder::files() on the folder you've specified. 
The folder is returned by 
Akeeba\ReleaseSystem\Admin\Model\Upload::getCategoryFolder by appending 
the (relative) folder name to JPATH_SITE which in turn is set by 
Joomla!. Unless there's an issue with ownership / permissions / 
open_basedir I don't see any other reason why this would return empty.

Except, of course, if you are trying to use a file which is already used 
in another download Item. As you may recall, only files which have not 
been used in other download items plus any already selected file are 
displayed in the drop-down.

FWIW I can't reproduce it with either Ubuntu Server 14.04 or 16.04. 
However, I am using my own LAMP setup, not the stock Ubuntu one. I am 
compiling and setting up my own PHP. Moreover, PHP runs over FastCGI, 
not as an Apache module (I need to be able to test with multiple 
versions of PHP).

**Comment by PierreCorell** [comment]
Hmm, I see the same issue on my side. No glue found. Since the update to 3.7.3 / 3.7.4 it does not getting uploaded files anymore.
on PHP 7.* and 5.6.31

no errorlog entry, no console error
