### ISSUE TITLE
HTML views aren't data views

### ISSUE THREAD

**Issue by mbabker** [akeeba/release-system#120]
There may be a reason for this, so before I crawl into a rabbit hole I might not want to be in, is there a particular reason the HTML views are inheriting from the base `FOF30\View\View` class versus `\FOF30\View\DataView\Html`?  One issue that's causing is that menu item parameters (i.e. metadata stuff) isn't being set.

**Comment by nikosdion** [comment]
It was a simple case of me having a brainfart when I was converting ARS from FOF2 to FOF3. I've now fixed that to inherit from the correct class. Thank you very much for the heads up!
