### ISSUE TITLE
State bleedover from categories to latest view

### ISSUE THREAD

**Issue by mbabker** [akeeba/release-system#121]
On a site with a latest releases view with no visual group filter and a categories view with a visual group filter, it is possible for the user state to bleedover from the categories view when navigating to the latest releases view which causes inconsistent data to be displayed.

Right now, the "best" fix I have is to do this at the end of the `Latest` controller's `onBeforeMain` method:

```php
// We potentially have bleedover of the user state when coming from a categories view
$app->setUserState($categoriesModel->getHash(), null);
```

The only reason I don't do this as a PR is I feel like there's got to be a more eloquent solution but right now I haven't stumbled upon it.

**Comment by nikosdion** [comment]
There was indeed a more elegant solution. I am going to make the solution even _more_ elegant at the FOF level ;)

**Comment by nikosdion** [comment]
See https://github.com/akeeba/fof/commit/8961f9c9c0531edd1e7cb699d38f10d651416622 for an even more eloquent solution.

Note that ARS now has a different default model in the Latest view. As a result I don't need to use the FOF 3.1.2-specific feature in ARS. But it's good to know if you ever bump into the same / similar issue in the future :)

**Comment by mbabker** [comment]
Awesome, thanks!
