### ISSUE TITLE
Release Date format

### ISSUE THREAD

**Issue by Bakual** [akeeba/release-system#123]
For the release date, we can only set the date, not the time (maybe due to new J3.7 calendar), but in frontend, the time part is shown, resulting in a bit strange times depending on timezone :smile: 
![date](https://user-images.githubusercontent.com/1018684/30531622-d243151e-9c4f-11e7-9822-a4bcc3c98487.PNG)

I think either the release date formfield should be set to allow time being entered or the date in frontend should be formatted to not show the time part.

**Comment by nikosdion** [comment]
If you type the time in the backend field and submit the form does it get stripped out? Also, have you tried using the Akeeba Release Maker instead?

**Comment by Bakual** [comment]
The time gets stripped out when I save the release form.

> Also, have you tried using the Akeeba Release Maker instead?

First time I hear about that, so no, haven't tried it :smile:

**Comment by nikosdion** [comment]
So, funny thing, the Calendar field in Joomla! 3.7 and later is broken. Even when I set `showtime="true"` it ignores it and strips the time from the input. Apparently I either have to write my own Calendar field or switch all Calendar fields to Text in all of my software.

Sorry, it would seem that Joomla! broke the feature it relies on to set the release date/time for its own distribution :man_facepalming:

**Comment by nikosdion** [comment]
Clarification: even though FOF 3's Calendar field doesn't _currently_ pass the `showtime` attribute I did make the necessary modification. For whatever reason the Joomla! field when confronted with the `showtime` attribute allows you to set the time in the popup but does not display the time in the field. It also strips any manually typed time, rendering the feature useless. I am trying to find a workaround. If only Joomla! would stop breaking what's working and start fixing what's _not_ working instead...

**Comment by Bakual** [comment]
If I remember right, the only change in behaviour of the calendar field is that it now more strictly respects the format parameter. Eg if you have specified "%Y-%m-%d" (or didn't specify a format), it will now strip the time part. Before it would just not display it when rendered but allow to enter it. One can see that as a small B/C break or also as a bugfix, depending on point of view 😄 

So you should be able to set the format to "%Y-%m-%d %H:%I:%S" (like should be done for a datetime field anyway) and it should work. The "showtime" parameter only affects if the calendar popup shows a time field or not.

However even better would be to use the new "translateformat" parameter. If that one is set to true, the the format is automatically generated based on active language and the state of "showtime". The "format" parameter is ignored in this case. Imho that's the best way to use the calendar field.

Btw: https://docs.joomla.org/Calendar_form_field_type is up to date.

**Comment by nikosdion** [comment]
From Joomla! 1.5 to Joomla! 3.6 the format only played a part in _displaying_ the timestamp. It would not modify the value on submit. Since Joomla! 3.7 the format now forcibly changes the value when submitting the form which is a backwards incompatible behavior change. Being a bug fix is irrelevant. When the behavior changes in a way that existing software breaks it's a b/c break and warrants a new major version if you are actually following semver (instead of pretending to).

The FOF field now reverts to the correct format and sets `showtime` to true as well. This restores the behavior of the field to what it was.

What you propose would be a different kind of b/c break. The format has to be Y-m-d H:i:s unless the developer specified differently.

**Comment by Bakual** [comment]
> From Joomla! 1.5 to Joomla! 3.6 the format only played a part in displaying the timestamp. It would not modify the value on submit. 

I know. But wouldn't you say that not displaying the time when the field actually allows to enter a time seems wrong? On a successive save, the time was removed again if not entered manually again.
That's why personally I didn't expect it to become an issue since most extension devs would have a format matching the field and personally I saw it as a bugfix. Obviously, most bug fixes change a behavior but it's not necessary a B/C.
Gladly, I didn't write that part (I suck at JS), I'm responsible for the translateformat part 😄

**Comment by Bakual** [comment]
Looking at your commit, I see you use the translated formats "DATE_FORMAT_CALENDAR_DATETIME" and "DATE_FORMAT_CALENDAR_DATE". If you do that, you will have to set the attribute "translateformat" in the field. Otherwise the form->filterfield method will fail depending on language because it can't parse the date format. Except of course if you have own code in FoF dealing with that.
