### ISSUE TITLE
HTTP Amazon URLs always returned

### ISSUE THREAD

**Issue by mbabker** [akeeba/release-system#125]
The Amazon S3 helper in ARS does not have a way to pass the `$https` parameter to the Connector when getting the URL.  This results in the default false value being returned and package URLs being returned using the HTTP protocol.  Adding a component parameter would be helpful to control the behavior.

**Comment by nikosdion** [comment]
I had forgotten to pass the HTTPS parameter to the connector. The value for it is already known: you select whether to use HTTPS with S3 in the component's Options. I have fixed this by passing this option to the connector as originally intended. Thank you for the heads up!
