### ISSUE TITLE
COM_ARS_IS_SUPPORTED translation missing

### ISSUE THREAD

**Issue by shoulders** [akeeba/release-system#133]
on the new (Akeeba Release System: Category Editor) page there is an untranslated string COM_ARS_IS_SUPPORTED

![image](https://user-images.githubusercontent.com/319997/35745184-498c973e-083a-11e8-9f92-0129c1209475.png)

I do not know what the string should say. I have check the com_ars for this string and the only place it is referenced is administrator\components\com_ars\View\Categories\tmpl\form.form.xml and it is not in the repository because the translations are else where.

Joomla 3.8.4
ARS 3.2.5

Thanks

**Comment by nikosdion** [comment]
This language string reads "Supported". This is a flag which does not do
anything in ARS. We use it in conjunction with the com_compatibility
component <https://github.com/akeeba/com_compatibility> to render the
Compatibility page <http://akeebabackup.com/compatibility.html> on our
site. This flag marks a release as currently supported (bug fixes and
new features on top of security updates).

Please note that com_compatibility, as it is, won't be of much use to
you. You'd have to at least override the
com_compatibility/View/Compatibility/tmpl/info.blade.php and
software.blade.php to make it work on a site other than our own.

**Comment by mbabker** [comment]
@nikosdion Actually I think that string is missing in your translation platform, it came from me with https://github.com/akeeba/release-system/pull/118 and I just tried a search on https://translate.akeeba.com/projects/ars/component_backend/en-GB/ for it with no result.

**Comment by mbabker** [comment]
Nevermind, found it, the search UI confused me (I tried searching by key, you have to search by translated string).  And it is indeed there.

**Comment by nikosdion** [comment]
Closing as invalid
