### ISSUE TITLE
Bug in #__ars_categories Create table SQL

### ISSUE THREAD

**Issue by hrtrulz** [akeeba/release-system#134]
In the #__ars_categories the is not , at the end of asset_id line 

 > `asset_id` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.'
 > `title` varchar(255) NOT NULL,

**Comment by application2000** [comment]
@hrtrulz just add a comma after the COMMENT part like this:

```mysql
asset_id int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
title varchar(255) NOT NULL,
```


repackage it and it will work.
Hope it helps.

**Comment by nikosdion** [comment]
This has been fixed in the current feature branch since January 5th with commit 0b480f52cc87c6b05ba2a52ac448eb8650a28304
