### ISSUE TITLE
Implement Joomla! 4 routing.

### ISSUE THREAD

**Issue by nikosdion** [akeeba/release-system#135]
See https://github.com/joomla/joomla-cms/issues/19537#issuecomment-363407642

Old function-based routers are not supported. We must have a router class extending RouterBase which lets us call our old function based routers into the methods required by that class, therefore having a solution compatible with Joomla! 3 and Joomla 4 at the same time.

**Comment by mbabker** [comment]
Just for reference, depending on how far back you're still supporting, the `JComponentRouterBase` class was added in 3.3 so you don't necessarily need so support both the functions and the classes.

**Comment by nikosdion** [comment]
Thank you! We were going as back as 3.4 and the next release cycle would drop anything older than 3.6. SO I guess we're completely covered by just implementing JComponentRouterBase.

Thank you very much, Michael!
