### ISSUE TITLE
Joomla 3.7 and 3.8

### ISSUE THREAD

**Issue by basd82** [akeeba/release-system#136]
Could you add the icon's for joomla 3.7 and 3.8 in the environments?

**Comment by nikosdion** [comment]
Past Joomla! 3.5 I gave up on creating new icons and resorted to using the generic 3.x icon: https://github.com/akeeba/release-system/blob/development/component/media/environments/ars-joomla3x.png  

You can create new environments yourself using that icon. The XML update stream names should be `joomla/3.7`, `'joomla/3.8` and so on.

I am not going to update the SQL of the installer. Adding environments like that is very error prone.
