### ISSUE TITLE
Sort Selection Lists by Title

### ISSUE THREAD

**Issue by murphylas** [akeeba/release-system#139]
Many of the selection lists are listed in the order of addition. This is a real problem when trying to find something in long lists. Please sort the selection lists by title. For example, when attempting to add an item, the categories are not sorted. So I have to scroll through the entire list to find a category.

**Comment by nikosdion** [comment]
## No support - For developers only

This software is provided **WITHOUT ANY KIND OF SUPPORT WHATSOEVER**. You are free to consult [the documentation](https://github.com/akeeba/release-system/wiki).

If you are a developer you are free to submit a pull request with your code fix, as long as there is a clear description of what was not working for you, why and how you fixed it.
