### ISSUE TITLE
Error Handling Problem When Creating New Categories

### ISSUE THREAD

**Issue by murphylas** [akeeba/release-system#140]
I was creating a category when I made an error on clicking Save. The form save the category and display a blank new category screen. I did this 3 times. Somehow the 3 categories were linked. If I deleted 1 category all three were deleted. So I had to go into phpMyAdmin and manually remove the duplicate categories.
Sometimes they appeared in the category listing. Other times, no.

**Comment by nikosdion** [comment]
## No support - For developers only

This software is provided **WITHOUT ANY KIND OF SUPPORT WHATSOEVER**. You are free to consult [the documentation](https://github.com/akeeba/release-system/wiki).

If you are a developer you are free to submit a pull request with your code fix, as long as there is a clear description of what was not working for you, why and how you fixed it.

**Comment by nikosdion** [comment]
I cannot reproduce this. I've tried Save, Save & Close and Save & New with either a new or an existing item, with various validation errors. Something stuck in your session? Caching getting in the way?
