### ISSUE TITLE
No labels on WYSIWYG fields

### ISSUE THREAD

**Issue by mbabker** [akeeba/release-system#143]
On the edit release page, the WYSIWYG editor fields don't have a label in the UI.

<img width="1385" alt="screen shot 2018-04-18 at 8 28 59 am" src="https://user-images.githubusercontent.com/368545/38934930-a3b147d6-42e2-11e8-9467-9ee98505145a.png">

**Comment by nikosdion** [comment]
I kinda did that on purpose :) In the not so distant future the release description will go away altogether and only the release notes (right hand side) will be kept.
