### ISSUE TITLE
Release form issues

### ISSUE THREAD

**Issue by Bakual** [akeeba/release-system#144]
I may miss something but when I create a new release the "Access" parameter is always saved as "Registered" the first time, even if explicitely set to eg "Public". A second save will make the selected option stick as expected.

Also in the same release form, the "Maturity" is by default set as "Beta". It may make more sense to either have no default (eg shows the "Select a maturity status" entry) or default to "Stable".

As a last (minor) wish, it would be nice if the "Categroy", "Maturity" and "Access" is preselected with the respective active filter selection from the "Releases" view.

**Comment by Bakual** [comment]
Forgot to mention that this is on the released 4.0.0 version.

**Comment by Bakual** [comment]
Just saw the same also applies when creating a new item (except the maturity ofc)

**Comment by nikosdion** [comment]
I honestly have zero time to address any of that right now since I'm mostly interested in finishing the GDPR compliance stuff for our company before the May 25th deadline. I also don't really care about these issues since ARS is an internal project and these issues do not affect us (we use Akeeba Release Maker to publish releases).

If you submit a PR I might be able to take a look and merge it. But as things are right now I am not going to spend any time on these.

**Comment by Bakual** [comment]
Unfortunately, I have no clue how your framework works. So I probably have to live with it if nobody else has knowledge and time to address it.
It's not a big issue anyway, just a minor thing.

**Comment by nikosdion** [comment]
I know this is a very old issue, but I just got the time to do a bit of spring cleaning :)

Testing against the latest development branch I can reproduce neither of these issues. The maturity is presented as Stable. The access stays whatever you select it.

Regarding filters in the Releases view populating the new release form page. The following filters are already reflected in the new release form page: category, maturity, access level, published status, language. That is, the filter is used to populate the default state of the new item.

If something is still broken feel free to re-open the issue.

**Comment by Bakual** [comment]
Yep you're right. Seems to be working fine now.
