### ISSUE TITLE
File size 0 KB when downloaded for some items

### ISSUE THREAD

**Issue by StarAzure** [akeeba/release-system#145]
For some items that I create, the file is 0 KB when users download it. I deleted the entire release and items and recreated but the item size when downloaded is 0 kb. This does not happen all the time for all items.
Developers may not know until users complain. I noticed this in the previous version as well and now with version 4.0 so I had to create an issue. This if for Normal and not bleeding edge.

**Comment by nikosdion** [comment]
Cannot reproduce. Sounds like a server issue. After all, ARS simply does a pass-through read of the file using standard PHP functions. Either your version of PHP is broken (unlikely) or your web server is misconfigured and does not relay the body of the download from PHP to the client.

**Comment by StarAzure** [comment]
I agree its hard to reproduce because it happens around 1 in 7 items for me. I have been using ARS for 5 years now and I never had this issue. My php version is 7.2.4.  Temporarily, I am using dropbox for the one item thats 0 kb. Also that item did not populate size, MD5 and SHA when saved.
I use siteground hosting and default settings which is used by a lot of Joomla developers. Here is my php info for com_ars folder if anyone can help - https://starazure.com/components/com_ars/phpinfo.php

When it happens, is there some logs or debug that I can set up to collect additional info ?

**Comment by nikosdion** [comment]
> While on the server, that item did not populate size, MD5 and SHA when saved.

Well, that's kinda important and you should have mentioned it :) This means that the item cannot be read by PHP. Not even its metadata. No wonder it downloads as 0 bytes! When PHP tries to read it to either get its size, its checksum or push it to the browser ("download") it cannot. You just solved the case!

I would check the permissions of the item, and all the folders it's in (and its parent folders, their parent folders etc).

It's also possible that you are using non-ASCII characters for the filename. They could also cause a problem depending on your database collation. However, I would assume that if that was the case you'd have already spotted a pattern.

**Comment by StarAzure** [comment]
Its not the file permission or the file name. Here is how I proved it. I assigned the category path to the same as another item's that works. Then I assigned the file of that working item to this item that did not work. The result is that the same file when downloaded from this item is 0 kb. Now this is bothering me more than it did 2 days ago.

**Comment by nikosdion** [comment]
How did you assign the same item? It's not possible to do that. Each ARS item stores the _relative_ path of the file to the category's directory. Two different categories would have a different path which would explain why you get a 0 byte download.

**Comment by StarAzure** [comment]
Let me explain.
category 1 > Release A > Item X (File ABC) - Is working fine

category 2 > Release A > Item Y (File XYZ) - 0 KB when downloaded

This is what I did to test that it is not the folder that's a problem:
1) Changed the path of Category 2 to that of Category 1
2) Then changed ZIP file used in the Item Y (which is still in category 2) to the zip file that was working for item X.

So after I changed, category 2 looked like this
category 2 (path of Category 1) > Release A > Item Y (File ABC) - Still getting 0 KB when downloaded

So if it was the folder or the file that was the issue then the change above should have fixed the issue because the same folder and File ABC is working for category 1 Item X..

**Comment by nikosdion** [comment]
So, the problem is that whatever is in the alias (URL slug) of the item is causing your server to barf. Which is a server issue.

**Comment by StarAzure** [comment]
I am sure its not the url or alias because I change it to just alphabets and there is no change. I am sure it will come up with someone. Until then I will keep using dropbox.

**Comment by nikosdion** [comment]
Here is an idea. Change the file type to URL and give the Dropbox link (make sure the last parameter is dl=1, not 0). Does the download work? 

If not, try changing the category alias to a completely different word (preferably something short to make sure the full URL does not grow beyond 150 characters which COULD trigger weird issues in some browsers and servers). Does it work now?

**Comment by StarAzure** [comment]
1) Changing to link with dl=1 works.

2) Also another work around is changing to link and using http path to the folder location on my server (https://StarAzure.com/download/folders/folders/.../itemfile.zip) also works. 

I didn't have to change anything else including the alias for the above 2 options to work. Looks like "File" does not work but "Link" works.
