### ISSUE TITLE
Verify if item is downloadable before downloading it to get better error messages in Joomla for subscriptions

### ISSUE THREAD

**Issue by svenbluege** [akeeba/release-system#146]
By using an installer plugin and the method `onInstallerBeforePackageDownload` I can update paid extensions. 

But the update will fail if the DownloadID is invalid. The Joomla error message is very useless and I want to improve this by checking the DownloadID in the `onInstallerBeforePackageDownload `method before using it.

I have two ideas how to do this: 

1. add a dummy release + item which contains a simple text file and needs a subscription level to get downloaded.
2. ARS supports in the Item controllers download task a parameter like "checkOnly=true". Instead of downloading the item, it would return [success|failed]. A dedicated task might work as well. 

If the check succeeds,  `onInstallerBeforePackageDownload` can modify the URL. Otherwise it would attach a message like "Subscription expired, blabla".

In both cases, we would end up with additional entries in the download logs since logging failed download attempts might still be a good idea.

What do you think?  Is there maybe a third way which is already in place?

**Comment by svenbluege** [comment]
I get your point and will check the database way. Thanks for the feedback!

**Comment by innato** [comment]
I hit this page because I was also considering using the `onInstallerBeforePackageDownload` method as mentioned by @svenbluege . Now I understand that this may be a bad idea. However, when I have a subscription-based purchase that expires, I would really like to redirect the updating website to a web page of mine where he/she can renew the subscription when the update fails. How could that be done without a `onInstallerBeforePackageDownload` process? My extension already includes a system plug-in, so an additional function is not a problem.

**Comment by nikosdion** [comment]
You can’t. 

Joomla has stopped showing the server error message when a package download fails. It only shows the HTTP error code (number). 

You’d probably have to implement a very complicated installer plugin which asks your server whether the subscription is active or redirect the customer to a renewal page. This has atrocious performance, opens your site to abuse and has security issues. 

In my experience the best thing you can do is absolutely nothing. The few people with expired subscriptions will overwhelmingly come to your site to download the package and see that their subscription expires. The other 0.008% of your subscribers will either contact you or give up. The former you can explain what to do. The latter... do you really care to spend so much effort about them? I wouldn’t.
