### ISSUE TITLE
Categories not displaying all the time

### ISSUE THREAD

**Issue by alan123489** [akeeba/release-system#147]
This is a minor suggestion for the documentation

I'm using

MySql Version: 5.7
PHP Version: 7.1.17
Joomla Version: 3.8.7
ARS Version: 4
Browser: Chrome

I set up a new category and saved (and closed) it.  I was then shown a page with all the current categories.  When I navigated away and came back they had vanished.  Strangely they were still in the drop down boxes on the other pages and in the database.

After a lot of playing about I realised that to see the categories you need to select the access level to be able to see them. Leaving it on default (-select an access level-) results in nothing being shown.  I assumed it would just show all the access levels and you'd use the filter  to narrow the search which seems to be the way the other sections work.

So as a suggestion to save others searching about it might be worth adding into the documentation that you need to select the access level when in the categories section to get the categories to show (assuming that this is the way it's supposed to work).

Great software anyway

Alan

**Comment by nikosdion** [comment]
It looks like I completely missed that issue because I confused it with a different issue I had replied to. Oops. I'll change the default access level to Public just like we do for releases.
