### ISSUE TITLE
Unpublished items show up in Latest Releases

### ISSUE THREAD

**Issue by thoni56** [akeeba/release-system#155]
I updated my very old ARS to the latest relase 4.1.0 (thanks for still making it available).

Although I know you don't officially support this any more, I thought I'd just record a problem I see with this new version.

I have this:

![bild](https://user-images.githubusercontent.com/204496/43990761-56749e0e-9d60-11e8-9729-b21139f7495e.png)

Notice that only three of the seven items are published. On the front page, I see this:

![bild](https://user-images.githubusercontent.com/204496/43990805-fdf0e26e-9d60-11e8-8a45-b9f9888b9979.png)

 which is what I expect, but using the "Latest Release" menu item, I get this:

![bild](https://user-images.githubusercontent.com/204496/43990824-458d89a6-9d61-11e8-8574-55f4c19ce31c.png)

Here we can see all items in the release, including the non-published ones.

(As a small side issue, the new styling for the heading is not working so well for here...)

**Comment by nikosdion** [comment]
You can fix this issue by replacing `components/com_ars/View/Latest/tmpl/generic.blade.php` with [this file](https://raw.githubusercontent.com/akeeba/release-system/c21598fe82036ce2d83108199711fd72f3472c94/component/frontend/View/Latest/tmpl/category.blade.php).

Regarding the styling, you can always do template overrides to style the pages in a way that's most appropriate for your site. The default styling is very generic and more of a guideline.
