### ISSUE TITLE
Where did the copy button go in Releases and Items?

### ISSUE THREAD

**Issue by royroosterz** [akeeba/release-system#160]
It seems the Copy button has disappeared from the Toolbar in the Releases and Items sections. Is there a reason this button has been removed and is it possible to put it back please?

Thanks!

<img width="822" alt="akeeba_release_system__releases_-_joomla3_-_administration" src="https://user-images.githubusercontent.com/2189689/50698176-895e7400-1044-11e9-8fa1-1bcf405e400d.png">

**Comment by nikosdion** [comment]
Already explained in https://github.com/akeeba/release-system/issues/112
