### ISSUE TITLE
New Version of Admin Tools Crashes ARS Item Forms

### ISSUE THREAD

**Issue by murphylas** [akeeba/release-system#174]
I updated to the latest version of Admin Tools. Now the ARS Edit Items Form gives out the following message:

Akeeba Release System - An unhandled Exception has been detected
500 Class 'FOF30\Form\Field\GenericList' not found

File &lt;root&gt;/administrator/components/com_ars/Helper/Html.php Line 172

**Comment by nikosdion** [comment]
Per the [README file](https://github.com/akeeba/release-system/blob/development/README.md) in this repository:

## INTERNAL PROJECT

This software is only meant to be used only on our site and caters only to our business goals.

We do not provide support for it. We do not take feature requests for it. We do not even provide downloads for it.

There is absolutely no guarantee whatsoever that any feature implemented today will be available in the future or that the component will continue to work the same or even exist. The project does not even follow semver.
