### ISSUE TITLE
Where is ARS 5.1.0?

### ISSUE THREAD

**Issue by alebak** [akeeba/release-system#183]
Hello,

I'm trying to update to ARS 5.1.0 but I get these messages:

`Warning
Error connecting to the server: 404
Before updating ensure that the update is compatible with your Joomla! installation.
You are strongly advised to make a backup of your installation before you start updating.`

`Error
Failed to download package. Download it and install manually from https://github.com/akeeba/release-system/releases/download/5.1.0/pkg_ars-5.1.0.zip.`

Where is ARS 5.1.0 file? 😪

Also I have this warning message in Items tab:

`Notice: Array to string conversion in ...\administrator\components\com_ars\View\Items\tmpl\default.php on line 31`

How to updated to 5.1.0 version and fix that?

I have installed:

- PHP 7.4.x
- Joomla! 3.9.24
- fof 3.7.1

**Comment by nikosdion** [comment]
We do not publish releases for ARS 5.x as explained in the project's README. You can follow the build process outlined in the README to build your own version. Check out the 5.1.0 tag, check out the `buildfiles` and `fof` repositories one level above the ARS repo's root. Then go into ARS' build folder and run `phing git -Dversion=5.1.0`. It will create the packages in the `release` folder inside the ARS repo.

FWIW I am working on a new incarnation of our release maker which means that I should _probably_ be able to make new releases for our internal projects available on GitHub sometime soon.

**Comment by laoneo** [comment]
If you are interested @alebak, I made a docker task to build ARS inside a container so you don't have to mess with dependencies.

**Comment by nikosdion** [comment]
@laoneo That would be an interesting thing to include in the README if you're willing to maintain that task for a while :)

**Comment by laoneo** [comment]
It's basically a docker compose file and a 28 line shell script (no magic, just a bit of git clone and cp). The script is not public yet as I only use it internally. But I can prepare a pr if you want @nikosdion.

**Comment by alebak** [comment]
@laoneo Yes, I am interested. If you can share it as @nikosdion says so much the better. Thank you.

**Comment by nikosdion** [comment]
ARS 6.0.0 will be released March 6th (or thereabouts). I plan on putting the release on our site's download sections but still offer it without support. As a result I feel I can now close this issue.

**Comment by laoneo** [comment]
Found the time and created a pr with a docker compose file which I'm using internally at Digital Peak to build ARS. An comments https://github.com/akeeba/release-system/pull/198?
