### ISSUE TITLE
Beeding Edge items are not editable anymore

### ISSUE THREAD

**Issue by helgator** [akeeba/release-system#185]
First a Thank You for the ARS which we use to distribute our Joomla component! 

For a few months now I cannot edit items that are uploaded via FTP in a Beeding Edge category. In the back end edit form I can edit such item but the Beeding Edge categories are not listed in the dropdown and the file dropdown is also empty. Updating to the latest pkg_ars-5.999.999.b1.zip build did not help.

**Comment by nikosdion** [comment]
The version you are using was, indeed, not showing the Bleeding Edge (BE) releases in the management and wouldn’t let you edit them. This will change in version 7 which is for Joomla 4 only — currently under development.

Please note that this is not, however, how Bleeding Edge is meant to work. You are supposed to use the Automatic Item Descriptions to create descriptions of the items in your BE categories. When the BE code detects a new folder it will create a new release and inside it one new item for each files you have in that folder using the automatic item descriptions.

If you find that you regularly need to edit BE items then BE is not the right category type for you. You need to use Normal categories. They don’t prevent you from using one folder per release in the server file system. In fact, I actually use them with one folder per release to keep things sane and manageable. They allow you to select any file per item which is not used by another item and you can edit all item and release properties.

BE is a tool for unattended publishing of development releases. The idea is that you upload a bunch of files in a new folder and you magically have a new development release published. That’s why editing these items is problematic. Even when it succeeds, your items may be reset next time the BleedingEdge code runs in the frontend of your site.e
