### ISSUE TITLE
Joomla 4 API weirdness

### ISSUE THREAD

**Issue by nikosdion** [akeeba/release-system#186]
This is for @wilsonge following our conversation on Twitter.

I observed two weird issues with the Joomla 4 API application implementation when working with ARS for Joomla 4 (see the feature/core-mvc branch in this repo) and [Akeeba Release Maker](https://github.com/akeeba/releasemaker) (development branch).

## PATCH requests return nothing even when the resource is updated

Let's say that I do this request to update a release with ID 81 which was previously unpublished:
```http
GET https://www.example.com/api/index.php/v1/ars/releases/81
Accept: application/vnd.api+json
Authorization: Bearer MY_TOKEN
Content-Type: application/x-www-form-urlencoded

data%5Bid%5D=81&data%5Bcategory_id%5D=1&data%5Bversion%5D=2.0.0&data%5Balias%5D=2-0-0&data%5Bmaturity%5D=stable&data%5Bnotes%5D=%3C%21--%0A++%7E+%40package++++AkeebaReleaseMaker%0A++%7E+%40copyright++Copyright+%28c%292012-2021+Nicholas+K.+Dionysopoulos+%2F+Akeeba+Ltd%0A++%7E+%40license++++GNU+General+Public+License+version+3%2C+or+later%0A++--%3E%0A%0A%3Ch3%3ERelease+highlights%3C%2Fh3%3E%0A%3Cp%3E%0A%09%3Cstrong%3EManual+testing%3C%2Fstrong%3E+of+the+releases.%0A%3C%2Fp%3E%3Ch3%3EChangelog%3C%2Fh3%3E%0A%3Ch4%3ECritical+bugs+and+important+changes%3C%2Fh4%3E%0A%3Cul%3E%0A%09%3Cli%3EFixed+a+security+issue%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Ch4%3ENew+features%3C%2Fh4%3E%0A%3Cul%3E%0A%09%3Cli%3EAdded+cool%2C+new+feature%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Ch4%3ERemoved+features%3C%2Fh4%3E%0A%3Cul%3E%0A%09%3Cli%3ERemoved+rotten%2C+old+feature%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Ch4%3EBug+fixes%3C%2Fh4%3E%0A%3Cul%3E%0A%09%3Cli%3EA+bug+of+unspecified+priority+was+afflicting+the+software%3C%2Fli%3E%0A%09%3Cli%3E%5BHIGH%5D+High+priority+bug+was+afflicting+the+software%3C%2Fli%3E%0A%09%3Cli%3E%5BLOW%5D+Low+priority+bug+was+afflicting+the+software%3C%2Fli%3E%0A%09%3Cli%3E%5BMEDIUM%5D+Medium+priority+bug+was+afflicting+the+software%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Ch4%3EMiscellaneous+changes%3C%2Fh4%3E%0A%3Cul%3E%0A%09%3Cli%3EMade+a+minor+change%3C%2Fli%3E%0A%3C%2Ful%3E%0A&data%5Bhits%5D=0&data%5Bcreated%5D=2021-05-21+12%3A48%3A18&data%5Bcreated_by%5D=70&data%5Bmodified%5D=2021-05-21+12%3A48%3A18&data%5Bmodified_by%5D=70&data%5Bchecked_out%5D=70&data%5Bchecked_out_time%5D=2021-05-21+14%3A04%3A03&data%5Bordering%5D=0&data%5Baccess%5D=1&data%5Bshow_unauth_links%5D=0&data%5Bredirect_unauth%5D=&data%5Bpublished%5D=1&data%5Blanguage%5D=%2A
```

I expect to receive either the modified resource or at least a confirmation that `published` was changed from 0 to 1. Instead I get the JSON string `[]`.

Tracing the code I see that PATCH ultimately calls [`ApiController::edit`](https://github.com/joomla/joomla-cms/blob/3a5984d03366f707ef842ee48051af194f68848f/libraries/src/MVC/Controller/ApiController.php#L354). However, this method simply returns after saving the record without calling the view. Compare that with what the `add` method does a few lines above and you'll see why there is no result returned.

IMHO this is bad form because PATCH requests are not idempotent, i.e. the state of the resource I PATCHed is _not guaranteed_ to be identical to the data I sent. Something else may have changed. In my case it could be the alias of an ARS Release or Item or the file size and file hashes of an ARS Item. Or it could be a hit counter, auto-incremented. In any case, I should be passed them back when I send a PATCH.

## PATCH does not accept partial patching

The above request is a massive overkill when I want to publish an item. I should be able to do the following, just like I was able to do it with FOF:

```http
GET https://www.example.com/api/index.php/v1/ars/releases/81
Accept: application/vnd.api+json
Authorization: Bearer MY_TOKEN
Content-Type: application/x-www-form-urlencoded

data%5Bpublished%5D=1
```

If I try that I get an error that several fields are required. If you trace the code you'll see that [ApiController::save()](https://github.com/joomla/joomla-cms/blob/3a5984d03366f707ef842ee48051af194f68848f/libraries/src/MVC/Controller/ApiController.php#L410) retrieves the data from the request and goes through the entire Form validation. There's a TODO item "Not the cleanest thing ever but it works". I agree that it's not the cleanest thing ever and I disagree that it works.

The first obvious problem is that forms are meant for user input and may not correctly reflect all internal data in the resource. The second obvious problem is that you are not loading the resource before applying the request data, therefore this will fail to validate partial data. The third and most important problem is that this an architecturally incorrect solution. You're already going through the Model's save() method which is ultimately responsible for validating the data. In fact, by default it goes through the Table to load the record and save any data you send it, therefore calling the Table's check() method which is where the buck stops: this is where you should write code to definitively decide if the data is complete for saving and/or clean it up, fill in anything missing that can be inferred and so forth.

So my suggestion is to toss the whole form validation thing and relegate validation, clean up and normalisation to the Table's check method which is the architecturally correct place to do this kind of thing.

**Comment by wilsonge** [comment]
Some of the patch stuff will be solved by https://github.com/joomla/joomla-cms/pull/34274 (won't be merged quite as is - needs a little reworking but in principle will solve both preloading of item + the response being rendered).

> So my suggestion is to toss the whole form validation thing and relegate validation, clean up and normalisation to the Table's check method which is the architecturally correct place to do this kind of thing.

I hear you but I don't think this will be how it works. Mostly because (not through a conscious decision but just how it's ended up playing out naturally over the last X years) form validation has ended up being a place of validating directly data related to the form field (e.g. is the folder form field a valid folder in a Joomla subdomain, is the select form field using a valid option etc) and the table validation has ended up being data aware application specific logic (is the alias unique for the table).

So we need to do both. As usual because we have this complete split between JModel and JTable - but is basically unsolvable in legacy MVC.

**Comment by nikosdion** [comment]
IMHO splitting the validation in two is just asking for trouble, especially if security-critical checks (“is this folder escaping above our application root”) is placed in the GUI-oriented validation. I understand where this is coming from, I still disagree with the architecture of it but I understand it's unfixable without breaking all core and most 3PD components. So, yeah, whatever.

At least pre-loading the resource before applying the PATCH and returning the PATCHed resource would address the main problem which is that the current implementation is not up to the JSON API spec despite what's promised. To me that's the most important factor to consider. I can still write my software in a way that treats form validation as an optional, GUI-level validator and Table check as the data validation's last line of defence 😉

**Comment by wilsonge** [comment]
> At least pre-loading the resource before applying the PATCH and returning the PATCHed resource would address the main problem which is that the current implementation is not up to the JSON API spec despite what's promised. To me that's the most important factor to consider

Should be in the latest nightly :)

**Comment by nikosdion** [comment]
Thank you!

**Comment by wilsonge** [comment]
@nikosdion have you had time to test in the recent RC’s? Just as I know you’re one of the people actually properly testing the API and I’m scared about it’s overall stability/quality

**Comment by nikosdion** [comment]
I have not and I am unlikely to touch Release Maker to use partial PATCHing in the future. Right now I am GETting the record, make any changes and then PATCH the whole thing back to the server. This worked great and still works great. Given that this bit of code is what allows me to publish 8 software releases in an afternoon instead of taking 2 hours per release I think I'll keep it the way it is and I know is working.

Regarding more refined points about using the API, stability is fine but the breadth of the information I can retrieve and send is extremely limiting. I wanted to sync articles between two categories in site A and site B. My idea was that I could get the information from site A using the API and push it to site B using the API. However, I do not get all of the article information. I get partial parsed contents of the params field which means I can't ever get custom field data or other data I have set up in 3PD extensions (e.g. Akeeba Engage comment preferences). Likewise, I cannot POST or PATCH this information using the API. I think it would have been much better if the API simply returned the raw params field. The API is meant to be consumed by machines, not humans. Castrating the powerful params field for the benefit of humans in a machine-consumable API seems somewhere between counter-intuitive and beating the purpose of having an API. I can't do remote operations without writing my own component so I am not even going to bother with Joomla API, you know?
