### ISSUE TITLE
Db error saving detected Bleeding Edge release

### ISSUE THREAD

**Issue by sakiss** [akeeba/release-system#188]
Hi Nicholas

I encountered that in a fresh installation (built from your current repo) in J4.

It cannot save the detected Bleeding Edge release due to database error.
```Field `ordering` does not have a default value```

![ARS_bleedingEdge](https://user-images.githubusercontent.com/1838041/133838374-c31779da-543f-4ad1-9803-d62d68d2a2c3.png)

Update: The same happens with the `#__ars_items` table, after attempting to save the detected files.

**Comment by nikosdion** [comment]
Thank you for the bug report! Please check the small changes I made into the three table files. They should address this issue.
