### ISSUE TITLE
Adding a new download ID results in 404

### ISSUE THREAD

**Issue by laoneo** [akeeba/release-system#196]
Somehow I can't add a new download ID, it always results in a 404 error. When I turn off SEf mode in Joomla, then it results in a 403 err0r as it tries to load a download id with id 87 which is from a random user.
So my question, is there something broken on my site or is there a bug in ARS. I tried to debug it, but I ended somehow in the hell of the router API. SO before I'm going to dig here deeper, just wanted to confirm if there is an known issue.

**Comment by nikosdion** [comment]
It is a known issue. Thank you for reminding me, I will take a look now.

**Comment by laoneo** [comment]
Thanks!!

**Comment by laoneo** [comment]
Let me know if I can help testing

**Comment by nikosdion** [comment]
Fixing this was a bit more complicated than I thought. Please check the latest development branch, it should be fixed now.

**Comment by laoneo** [comment]
Looks god. The only functionality which is not working is that after a new dlid is created/rest/deleted, it redirects to the startpage.

**Comment by nikosdion** [comment]
Have you created a menu item for the Add-on Download IDs menu item type? It should redirect back there. At least it does on the two testing sites I have.

If not, check the controllers. Do they pass the return URL correctly to the view?

**Comment by laoneo** [comment]
Forget my last comment, I had a redirect in htaccess from the early times, where ARS had issues on update streams when joomla was in a subfolder. All is working good now.

**Comment by nikosdion** [comment]
Awesome! Thank you for the feedback :) Have a great weekend!
