### ISSUE TITLE
Arslatest plugin throws an error

### ISSUE THREAD

**Issue by maggus** [akeeba/release-system#202]
### Problem
It seems that the {arslatest} content plugin throws this error in any situation:

```
0 Call to a member function getItems() on null
```

### How to reproduce

1. New installation of Joomla! 4.0.6
2. New installation of ARS Package 7.0.4
3. Minimal editing of ARS: 1 category, 1 release, 1 item (http://test.ruhepotential.de/index.php/akeeba-release-system)
4. New Article with content {arslatest release 1} (http://test.ruhepotential.de/index.php/arslatest-plugin)

### Possible solution
#203 

### Screenshots

**Backend**
![screenshot_01](https://user-images.githubusercontent.com/1286126/152532202-7d24646a-13eb-4a35-9a50-725d70ff6f37.png)

**Frontend 1**
![screenshot_03](https://user-images.githubusercontent.com/1286126/152532207-5293bb27-d331-4205-a70c-0ce2ec1a06e3.png)

**Frontend 2**
![screenshot_02](https://user-images.githubusercontent.com/1286126/152532204-79fab912-75f5-4b1e-b175-e03339758664.png)

**Comment by nikosdion** [comment]
Your PR is correct and does solve the problem (which only happens on case-sensitive filesystems, i.e. on Linux).

The reason you don't see the latest release with `{arslatest release 1}` is that the release or the category are not public or, more accurately, your current user does not have view rights for one of them. Only releases you can view on categories you can view are taken into account by the plugin.

**Comment by maggus** [comment]
Thank you for explanation 👍
