### ISSUE TITLE
Add category image field

### ISSUE THREAD

**Issue by kulbabskyy** [akeeba/release-system#212]
Hi @nikosdion, thank you for the great extension. 
It is possible ask you to **add a category image field**, to display software icon/logo, it will be very useful.

Thank you!

Best regards,
Anatoliy Kulbabskyy

**Comment by nikosdion** [comment]
This software is designed to primarily fit the needs of our business site, akeeba.com.

As per the README, if you decide to use this software please keep the following in mind:

* We do not provide any support for this software whatsoever.
* **We do not take feature requests for this software.**
* There is absolutely no guarantee that any feature implemented today will be available in the future, including the next minor release.
* There is absolutely no guarantee that the component will continue to work the same or even exist.
* This project does NOT follow semantic versioning.
* We provide VERY irregular downloads.

For your use case, you can write a template override. You already have the alias of the category. Therefore you can create CSS classes with the alias. You can then add some CSS to your template (e.g. through its user.css file or similar) to display a category-specific icon. This is what we do. See https://www.akeeba.com/download/official.html The icon classes next to each category come from a function in the template override which maps category names to icon classes.
