### ISSUE TITLE
Access level for automatic item description

### ISSUE THREAD

**Issue by laoneo** [akeeba/release-system#213]
Would it make sense to have an access level setting for automatic item descriptions? This level will be then applied to items, when the description is used. If yes and you would accept a pr, then I can do that in the next days.

**Comment by nikosdion** [comment]
I would only consider that if it's optional and the default is to not set an access level. I understand the use case but it cannot clash with my use case (deploying with Akeeba Release Maker which sets the access level over the API application).

**Comment by nikosdion** [comment]
And by consider I mean I would very much merge it. Sorry, it wasn't clear on my part.

**Comment by laoneo** [comment]
Sure, initially the value will be empty.

**Comment by laoneo** [comment]
Pr has landed #214
