### ISSUE TITLE
Some problems with actions buttons in the backend

### ISSUE THREAD

**Issue by kulbabskyy** [akeeba/release-system#217]
Hi Nicholas, since 7.0.8 i have a some problems with actions buttons in the backend that is not working. Can you please check?

1. Publish/Unpublish not working by clicking on the icon in the "Items" and "Releases" section
2. Delete button not working in the "download logs" section (pull request)

Thank you

**Comment by nikosdion** [comment]
It was a small typo in both backend pages. It's now fixed. Thank you for reporting this!
