### ISSUE TITLE
Direct links are only working for none guests

### ISSUE THREAD

**Issue by laoneo** [akeeba/release-system#223]
As you can see here https://github.com/akeeba/release-system/blob/development/component/frontend/src/View/Items/HtmlView.php#L133. Direct links are only working for none guests. Is this intended? This issue came up while testing #220 as a public user. It never worked because $directLink is always false from here https://github.com/akeeba/release-system/blob/development/component/frontend/tmpl/items/item.php#L20.

**Comment by nikosdion** [comment]
This is correct and it's always been like that.

The DirectLink appends the Download ID to the download URL, allowing you to paste it to Joomla's Install from URL.

If you are a guest you don't have a Download ID, since the Download ID is an account identifier.

If you have a public item which doesn't need a Download ID you can always copy the download URL provided by the download “button” (which is actually just a styled link).

**Comment by laoneo** [comment]
This means the show unautorized feature for items is only working for logged in users. I was thinking more of the use case to show all the downloads to guests and then redirect them to the subscribe page when they want to download a paid extension, the !$user->guest check prevents that use case. I mean I can still remove the check in the override, but was wondering what I miss here. So should I close this issue then?

**Comment by nikosdion** [comment]
The DirectLink does not affect your use case.

Let's say you have the Category and Release access set to Public, but the Item itself set to Subscriber (an access level for subscribers), with the Item's Show Unauthorised Links set to Yes and the unauthorised link URL set to `https://www.example.com/subscribe` (your new subscription page).

When you access the Release page as a guest you see the Item. Its name, filename, and Download button all link to `https://www.example.com/subscribe`, thus accomplishing the goal you had in mind.

When you access the Release page as a subscriber you see the Item, too. However, its name, filename, and Download button all link to the actual download URL of the item. Furthermore, you see the DirectLink button which is the same download URL plus `?dlid=THE_DOWNLOAD_ID_OF_THE_USER`.

This is already possible. It's how it already works.

Am I missing something in your use case?

**Comment by laoneo** [comment]
That's exactly the use case I'm talking about which is not working for me as public user. the [$directLink variable](https://github.com/akeeba/release-system/blob/development/component/frontend/tmpl/items/item.php#L20) is always false, because `$this->directlink` is always false for not logged in user.

But I'm not sure if fc4d966a796aab3c5233a96dfb3161ef32f2a54b fixed that issue as well, need to test it.

**Comment by nikosdion** [comment]
It should have fixed this. It separated the “do I have an actual download link” from the ”does the download link also allow for a DirectLink” because they are two different use cases.

**Comment by laoneo** [comment]
It is fixed indeed.
