### ISSUE TITLE
Adding custom checks before allowing a download

### ISSUE THREAD

**Issue by tassosm** [akeeba/release-system#224]
I want to create my own checks to determine whether the user is allowed to download a file. 

I noticed you're triggering the `onARSBeforeSendFile` event before sending the file to the browser. 

Is listening to that event the best way to go?

**Comment by nikosdion** [comment]
This event is normally used to modify the file to be downloaded. Of course you can throw a RuntimeException to stop the download. 

The other events raised by the controller work before we've resolved the Download ID to a user; those would be even less useful.

So, yeah, I guess this event is the best one for your use case.

**Comment by tassosm** [comment]
Thank you!
