### ISSUE TITLE
Additional DLIDs are not working. Error connecting to the server: 403

### ISSUE THREAD

**Issue by kulbabskyy** [akeeba/release-system#229]
Hi Nicholas, it seems that the additional DLID`s is not working after the latest update.
It returns error 403 on Joomla extension update attempt (but accessing URL like _https://site.com/xxxxx&dlid=123:xxxxxx_ via browser  still working correctly).

In the same time the **main download ID is working as expected**.

Can you please check this?
Many thanks!

Best Regards,
Anatoliy

**Comment by nikosdion** [comment]
That cannot possibly be right. We use ARS on our site, and add-on Download IDs are used extensively. I literally just tried that on our own site and it works.

I do, however, notice a pretty major issue in your URL. You are not URL-encoding the colon.

The colon in the Download ID **MUST** be URL-encoded. For example, this URL is **WRONG**: `https://www.example.com/download/example/1-2-3/pkg-example-1-2-3-pro-zip.zip?dlid=12345:abcdef0123456789abcdef0123456789`. The correct URL is `https://www.example.com/download/example/1-2-3/pkg-example-1-2-3-pro-zip.zip?dlid=12345%3Aabcdef0123456789abcdef0123456789` (the colon is URL-encoded as `%3A`).

**Comment by kulbabskyy** [comment]
Hello Nicholas, thank you for the reply. 

Sorry it was my fault, i have disabled the bootsrap in the theme settings and the published/unpublished icons on the API key managment page (frontend) was not visible. Those additional donwload keys was disabled. So once i have enabled it works as expected while using Joomla update system. 
_I`m using URL-encoding, i have posted the link in that format for better redability._

But as i see now, those disabled keys are still valid while accessing file download via URL? 
For example i can download a file via disabled API key by using a link like:
`https://www.example.com/download/example/1-2-3/pkg-example-1-2-3-pro.zip?dlid=12345%3Aabcdef0123456789abcdef0123456789`

While using a Joomla update system those disabled keys returns 403 error as it should be.

Can it be possible that in the Akeeba Release System 7.2.0 it was not fully fixed in case accessing the files via URL?

```
Akeeba Release System 7.2.0
[HIGH] Disabled Download IDs were still considered valid
```

**Comment by nikosdion** [comment]
I don't understand what you are saying.

As things are _in the current state of the `development` branch_:

* If you use your Main ID (which cannot be unpublished) you can download
* If you use a **published** add-on Download ID, properly URL-encoded you can download
* If you use an unpublished add-on Download ID, properly URL-encoded you can **NOT** download
* If you use an add-on Download ID which is not properly URL-encoded _I cannot tell you what will happen_ as it depends on your server configuration

This is exactly how the software is supposed to work.

Therefore there is no further action for me to take, other than closing this issue as invalid.

**Comment by nikosdion** [comment]
PS: It does not matter whether you try a download URL as part of the Joomla! extensions update process, the Joomla! install from URL process, a web browser (AS LONG AS YOU ARE NOT ALREADY LOGGED INTO THE SITE – IF YOU ARE LOGGED INTO THE SITE THE PRESENCE OF A DOWNLOAD ID DOES SOD ALL!), wget, curl, or whatever HTTP(S) client have you. The client is an _irrelevant_ detail for what I would like to believe is obvious reasons.

Based on the above part in all caps, is it possible that you were trying the URL with an unpublished Download ID from a browser which is already logged into the site, therefore completely ignoring the Download ID? Remember, the Download ID is only parsed if Joomla! reports that the URL is being accessed by the Guest user (`\Joomla\CMS\Factory::getUser()->guest` is non-zero) _and_ there is a `dlid` URL parameter. Anything else would be ignored.

**Comment by kulbabskyy** [comment]
Hi Nicholas, thank you for the clarification. Once the user logged in on the website, the download Stream displays another URL that is ignores DLID, i did not know that. Now i understand the logic, sorry to reported the non exist issue.
