### ISSUE TITLE
Wrong SEF routing on Categories list

### ISSUE THREAD

**Issue by peterader** [akeeba/release-system#230]
Hi Nicholas,

I'm aware this is an internal project and no support is provided whatsoever. That's not what I'm expecting here. I happen to use this extension and noticed a bug (so I believe). I can't figure it out myself and thought I would humbly let you know.

I have a top level menu item "Akeeba Release System » Categories – Normal categories" to show a list of all categories. Then there are sub menu items "Akeeba Release System » Releases" for each of the categories.

The issue I'm seeing is that the category SEF URL on the categories view is the same for all categories. It's using the one of the first submenu item. If I unpublish all submenu items the URL's are correct. I tried debugging it and the category_id and Itemid used before passing it to the Route::_ method are correct. However what comes back from the router is the same for all cases.

I tried both config settings of "Use ItemID to build SEF URLs" but it doesn't make a difference.

Let me know if that's not clear and I will try to describe it better.

Also, thank you for keeping this repository public. Highly appreciated. Let me know if I can buy you a beer somehow ;)

Best regards,
Pete

**Comment by nikosdion** [comment]
Your setup will not work. You need a top level menu of the type "Categories - Entire Repository". Under it you can have the "Categories - Normal Categories" menu item and/or individual Releases menu items.

It's best to use a hidden menu to organise your downloads repository. Then use Alias menu items inside your visible menu to provide visual structure.

**Comment by peterader** [comment]
Hi Nicholas and thanks for taking the time to get back to me.

Your reply gave me hope that it's something simple I can easily fix but unfortunately it didn't work. I tried every possible combination but it's still the same. I created a menu "Categories - Entire Repository" on the top level and then "Categories - Normal Categories" and also several "Releases". It doesn't make any difference how I nest the items. Either all on top level, all nested under "entire repo" or nested on multi levels. The SEF URL's for all items on the "entire repo" AND "normal categories" list are always the one from the first "releases" item, based on item order. Once I unpublish the "Releases" m
/enu items everything works correctly.

(I'm on Joomla 4.4.2 and release-system 7.3.2.)

I created a fresh test site with nothing installed other than release-system and created the menu structure to make sure it's not something on my existing site to cause this issue. You can take a look yourself. https://freakedout.cloudaccess.host/index.php/downloads-all 
I'll email you the admin login in case you want to take a closer look and modify things.
