### ISSUE TITLE
S3 hosted files all have same file size when imported via CLI

### ISSUE THREAD

**Issue by mbabker** [akeeba/release-system#71]
I'm doing a batch import of items into the `joomla.org` project site and for each record that gets created, the file size is always the same (1805173).  I watched the tmp directory during part of the import and saw that the temp.dat file is changing file sizes, so it seems the file is getting correctly downloaded.  Also, the hashes are unique per item.

Records I've created on the site via the GUI get the correct size attribute.

```php
// Use the F0F Platform to get all of our data
$platform = F0FPlatform::getInstance();

// Get a user object for my account
$user = $platform->getUser('michael.babker');

// ID: 281
$item = array(
	'title' => 'Joomla! 1.0.14 to 1.0.15 Patch Download (.tar.bz2)',
	'description' => '<p>This package is for performing updates from Joomla! 1.0.14 to 1.0.15</p>',
	'type' => 'file',
	'filename' => 'Joomla_1.0.14_to_1.0.15-Stable-Patch_Package.tar.bz2',
	'environments' => array('4'),
	'release_id' => '16',
	'created' => F0FPlatform::getInstance()->getDate('2008-02-22 23:00:00', new DateTimeZone('UTC'))->toSql()
);

// Add additional data for the record
$item = array_merge($item, array('created_by' => $user->id));

// Reset the table cache on each iteration
F0FTable::forceInstance();

/** @var ArsModelItems $itemsModel */
$itemsModel = F0FModel::getTmpInstance('Items', 'ArsModel');
$itemsModel->save($item);

if ($itemsModel->getErrors())
{
	foreach ($itemsModel->getErrors() as $error)
	{
		var_dump($error);
	}
}
```

**Comment by nikosdion** [comment]
Have you tried with the latest development branch? I have switched to Amazon's SDK for PHP (pulling it under a custom namespace to prevent some very interesting issues with different extensions using different and very incompatible versions of Guzzle...).

**Comment by mbabker** [comment]
If it's "stable enough" I'll give it a try.

**Comment by nikosdion** [comment]
As far as I could tell from my testing, it’s very solid

**Comment by mbabker** [comment]
Compiled a `com_ars-rev3A76A9A` package, updated the site, and ran my script again.  Still have the filesize issue.

**Comment by mbabker** [comment]
And just for completion, after this last import I went into the admin GUI and blanked out the size on an item then resaved it, the proper filesize was stored then.

**Comment by nikosdion** [comment]
I'll have to take a look. I don't understand where the wrong file size comes from. You said it only happens with S3?

**Comment by mbabker** [comment]
I'll have to test with a local file storage to check this.  Everything's been geared toward S3 so far.

**Comment by nikosdion** [comment]
I think I understand what is going on. You are running the import in a loop. On each iteration you call `$itemsModel->save($item);` which ends up calling the check() method of ArsTableItem. As you can see, the remote files is downloaded into the file temp.dat located inside Joomla!'s temporary directory, then its filesize is read with `filesize()`. However, PHP caches the size of the file in its stat cache the very first time you try accessing this file.

There is a workaround. On each loop iteration, right before `$itemsModel->save($item);` add:

```php
$config = JFactory::getConfig();
$target = $config->get('tmp_path') . '/temp.dat';
if (is_file($target) && !unlink($target))
{
	JFile::delete($filename);
}
clearstatcache();
```

This should remove any leftover files (there shouldn't be any unless you kill the script mid-import) and clear the PHP stat cache.

**Comment by mbabker** [comment]
With that in place, it's good to go!
