### ISSUE TITLE
Cannot build package from Git due to missing dependency

### ISSUE THREAD

**Issue by mbabker** [akeeba/release-system#72]
The link task has a dependency to a `usagestats` directory/repo that isn't publicly accessible.  When I ran the `phing git` task, it failed because the linked directory doesn't exist.

I'm getting around this for now using the directory from the 2.4.3 release.

**Comment by nikosdion** [comment]
Your workaround is correct. The usagestats repository is currently private. At some point I'll have to move the library code to its own public repository.
