### ISSUE TITLE
S3 Content-Disposition header

### ISSUE THREAD

**Issue by anibalsanchez** [akeeba/release-system#83]
Hi,

I have been debugging a case where new releases cannot be installed, with message Error updating COM_INSTALLER_TYPE_TYPE_.

CURLOPT_FOLLOWLOCATION is false, then Joomla Installer helper redirects the signed GET request to Amazon S3 http://..../com_.....zip?AWSAccessKeyId=....&Expires=....&Signature=... Finally, it downloads a file not ending with zip.

I think this case can be solved adding Content-Disposition header (GET parameter response-content-disposition=filename%3Dcom_.....zip) in S3Signature/createPresignedUrl ... or may be S3Client/getObjectUrl.

Please, let me know if I'm on the right path ... or there is something I'm missing.

**Comment by nikosdion** [comment]
The theory is sound. It should work. Well, there's only one way to know: try making that change, test it with a Joomla! installation which didn't work previously and if it works submit a PR :)

**Comment by anibalsanchez** [comment]
Hi,

One quesion, now S3Signature.php is merged, I have tested it with Signature V2, does the change have to also be implemented for Signature V4? Or, has S3Signature.php change already updated Signature V4?

**Comment by nikosdion** [comment]
To the best of my knowledge –and as far as the S3 API docs go and the AWS SDK for PHP code demonstrates– the V4 API does not concern signed URLs. They are always created in the old (v2 API) way.

**Comment by nikosdion** [comment]
Sorry to come back to this after a while. I was working on Amazon S3 v4 API integration yesterday and it appears that you *can* have pre-signed URLs with v4 signatures. I'm currently in the process of implementing such a connector in https://github.com/akeeba/s3

Right now that code only allows v2 presigned URLs and has a fixed chunk size for multipart uploads, but I'm working on it :)

**Comment by anibalsanchez** [comment]
Cool. Let me know if there is anything I can do to help.

**Comment by nikosdion** [comment]
Can you modify the `Connector::getAuthenticatedURL` method in the new repo to add a response-content-disposition HTTP header? I will do the rest of the work required for V4 signatures in the `Signature\V4` class.

**Comment by anibalsanchez** [comment]
Sure. Right now I don't a dev setup for ARS. I would need 2-3 days to test it.

**Comment by anibalsanchez** [comment]
My first estimation of 2-3 days was wildly opimistic. I still have to find time to update to ARS 2.5.1 and check how V4 signatures and response-content-disposition HTTP header interact.

**Comment by nikosdion** [comment]
OK, we'll wait :)
