### ISSUE TITLE
[3.0] Pages That are Children of Menu Items Defaulting to 'raw' Format

### ISSUE THREAD

**Issue by mbabker** [akeeba/release-system#86]
Upgrading test environment from ARS 2.5.1 to 3.0.0, reconfigured menu items post-upgrade for new component structure.  When browsing the site, my menu items (Latest Releases and Entire repository) render fine, but child pages of the Entire repository menu item are defaulting to the 'raw' format.  A var_dump of the `$_REQUEST` superglobal on one of these pages at the `components/com_ars/ars.php` entry point shows this data:

```php
$_REQUEST = [
    'Itemid' => string '38'
    'option' => string 'com_ars'
    'view' => string 'Categories'
    'task' => string 'download'
    'format' => string 'raw'
    'layout' => string 'repository'
];
```

On the Entire repository menu item's page, `$_REQUEST` looks like this:

```php
$_REQUEST = [
    'Itemid' => string '38'
    'option' => string 'com_ars'
    'view' => string 'Categories'
    'layout' => string 'repository'
];
```

Joomla 3.5.0-beta ARS 3.0.0

**Comment by nikosdion** [comment]
I am trying to reproduce that with the current development branch on Joomla! 3.4.5 and 3.5.0 BETA1 but I can't :(

I have a menu item for Entire Repository. All links generated from it work correctly and do have format=html. I am using Joomla!'s own SEF router, using Apache mod_rewrite. MAMP 3.4 with PHP 5.5 and 5.6.

Are you sure you're not doing something with overrides? I think that both this and gh-85 are caused by some template override somehow producing links with format=raw. That would explain both issues you are experiencing.

**Comment by wilsonge** [comment]
In arsParseRoute if the format isn't in the input we fall back to the last 4 chars. If in Joomla url suffix isn't enabled then this fails (the switch is just looking at the last 4 letters of the alias) and we fall to using the raw route. (N.B. This isn't me replicating but writing up a summary of the conversation me and Michael had about this last night)

**Comment by wilsonge** [comment]
So when we enabled URL suffix's this worked as expected

**Comment by mbabker** [comment]
Positive it's not overrides.  As George pointed out, when I turned on SEF URL suffixes the format started being read correctly and things started coming together.  With suffixes off, `arsParseRoute` would get `$format = null` from JInput then run into the condition where it would try to pull the suffix from the last few characters of the route.  On `/extensions/releases/podcast-manager/podcast-manager-1-6-beta-2` the format was "ta-2" and went into the default case of the switch condition, which treated the route as a raw format.

So this and #85 are probably the same issue in two different paths.

**Comment by mbabker** [comment]
And for reference I completely disabled my 2.5 overrides when updating to 3.0 (assuming they wouldn't work anyway), so unless FOF somehow reads `com_ars_old` in the template's HTML folder... :smile:

**Comment by nikosdion** [comment]
Commit https://github.com/akeeba/release-system/commit/20e22f79f38aa66989fcf544993668a9b0a72489 should fix that issue as far as I can tell from my test site. Can you please confirm?
