### ISSUE TITLE
[3.0] Latest Releases Displaying Incorrect Records

### ISSUE THREAD

**Issue by mbabker** [akeeba/release-system#87]
On the Latest Releases page, I'm getting the oldest releases for each of my categories.  Just playing with the raw queries, it seems like the GROUP BY clause is limiting records right but not retrieving the intended rows.  Breaking it down to the simplest query possible:

```sql
SELECT * FROM jos_ars_releases GROUP BY `category_id` DESC`
```

Joomla 3.5.0-beta ARS 3.0.0 MySQL 5.6.22

**Comment by nikosdion** [comment]
I cannot reproduce this with the current development branch :(

**Comment by mbabker** [comment]
Finally got my test server running after forgetting to stupidly install one of the PHP extensions I'd need.

http://104.131.33.179/extensions/latest shows the latest releases page with the oldest releases page and will let you hit the ACL issue (which like I said I'm more inclined is just a side effect of #86) if you try browsing around.  I've got debug mode turned on for the moment so that should help you get any relevant data.

**Comment by nikosdion** [comment]
Funny what a wrong grouping of MySQL arguments can do to a query. Also, having records created the inverse order of release numbers on a dev site is very fun when trying to reproduce and debug this issue. Good thing I could just use a dump of my live site instead :p
