### ISSUE TITLE
PHP Notice in the Normal Release View

### ISSUE THREAD

**Issue by wilsonge** [akeeba/release-system#93]
![image](https://cloud.githubusercontent.com/assets/1986000/12028757/8bb499ee-add4-11e5-8444-11f218e8a44c.png)

**Comment by nikosdion** [comment]
Can you trace it back to something in particular? The trace isn't helping. View.php line 14 is a `use` statement :s

**Comment by wilsonge** [comment]
Bare with me. I did this then suddenly realised the routings going completely wrong somewhere :( going to go back to the original backup and upgrade again.

**Comment by wilsonge** [comment]
OK So i think actually this is some kinda horrific routing issue - but i'm struggling to nail what the hell is going on still.

So on Akeeba Release System 2.5.2 the latests page gives me:
![image](https://cloud.githubusercontent.com/assets/1986000/12064610/796d110c-afbf-11e5-9085-1a081e8e1543.png)

I upgrade to 3.0.3:
![ars 3 0 3 install](https://cloud.githubusercontent.com/assets/1986000/12064613/83703788-afbf-11e5-9d48-fb04161bc117.png)

And then the page looks like:
![image](https://cloud.githubusercontent.com/assets/1986000/12064618/9a871e82-afbf-11e5-8961-17ffaba73337.png)

i.e. something totally different (all the template overrides are .php so they aren't being used and even if they were - this is totally different content).

As this is my windows local dev area I'm wondering if this is some kind windows bug - cause I'm sure that @mbabker would have come across this otherwise when he was doing the first round of testing the ARS 3.x upgrade.

I also tried "fixing" the menu items to the new style views rather than the old ones to rule out any kind of legacy routing being the cause.

**Comment by wilsonge** [comment]
![image](https://cloud.githubusercontent.com/assets/1986000/12064670/3d74ddc2-afc1-11e5-904f-8939065287a6.png)

This is the direct line causing the error in case it helps. But I *think* it's something more than that.

**Comment by mbabker** [comment]
When I last was working on updating my site's install, I ended up reconfiguring all the menu items for the new version; I don't think I tried browsing the frontend with the 2.5 menu configuration in place after the 3.0 upgrade.  Give that a shot perhaps?  Otherwise I'll try pulling a backup to my dev server and see what happens.

**Comment by nikosdion** [comment]
You definitely need to redo the menu items. Also make sure there is at least one menu item pointing to the whole repository, even in a hidden menu.

**Comment by wilsonge** [comment]
I did try it without much success first time round for the main menu items. But didn't check hidden menu items. So will try again and see how that goes and report back tomorrow

**Comment by mbabker** [comment]
There aren't any hidden menu items for ARS.  The only thing in the hidden menu is the link for the login page.

**Comment by mbabker** [comment]
Something's definitely off with the menu item config and routing when a visual group is involved.  We've got two latest releases pages that have a visual group filter on them (one for CMS downloads and one for the 3.x translation packs).  On both pages, the latest releases for the whole repository are showing up.

Then we've got 4 Normal releases menu items (one for each of the visual groups; CMS downloads, 1.5, 2.5, 3.x translations).  On each of those pages, all of the categories for all of the visual groups are being displayed.

All the single category/release pages are fine, it looks just to be something specific to the visual group filtering at least with these two views.

**Comment by wilsonge** [comment]
I've found a fix for the visual groups filter - will PR that when I get home. The PHP notice however I can't find the fix to the php notice

It comes from not finding the sub property normal on this line https://github.com/akeeba/release-system/blob/development/component/frontend/View/Categories/tmpl/normal.blade.php#L14

Can you advice at all @nikosdion on what's going on there?

**Comment by wilsonge** [comment]
Fix for the visual groups https://github.com/akeeba/release-system/pull/95

As I said @nikosdion if you could advice on that line that is giving the PHP Notice it would be appreciated :)
