### ISSUE TITLE
Latest Releases menu type shows unauthorized items

### ISSUE THREAD

**Issue by tassosm** [akeeba/release-system#99]
Latest Releases menu type shows unauthorized Items even if the Items are restricted to certain Subscription Levels and if the Category and the Release are set to Public. 

The reason the Category and the Release are set to Public is because I provide Free and Paid versions of my extensions and needs to be accessible to Guests.

Category, Release and Items have "Show unauthorised links" option disabled as well.

Akeeba Release System 3.1.1
Cache Disabled

**Comment by nikosdion** [comment]
Closed with commit bb07ed554d0446f4a27790a5102303821e80cc33  

Please update the files in components/com_ars/View/Latest/tmpl with the files of commit bb07ed554d0446f4a27790a5102303821e80cc33 and remember to clear the cache

**Comment by tassosm** [comment]
You are so fast! It works.
Thank you.
